### ISSUE TITLE
How can I calculate the position of the atom?

### ISSUE THREAD

**Issue by Hegel991** [dschick/udkm1Dsim#104]
When I use the method "add_atom(atom, position)" to build a unit cell, I am quite confused that how to calculate or confirm the position of the atom. Are there any tips or instructions for this? Thanks!!!

**Comment by dschick** [comment]
Hi @Hegel991,

thanks for asking. There is an [example in the docs](https://udkm1dsim.readthedocs.io/en/latest/examples/structure.html#Unit-Cells) which should include most of the details.
It is important to note, that the position is relative to the actual c-axis of the unit cell.
Since the simulations are 1D only, the position in the a-b-plane is irrelevant.

Hope that helps. Let me know if you have any further questions.

Best

Daniel

**Comment by Hegel991** [comment]
Hi @dschick,

Thanks for answering. It helps. In addition, this is a great job! 🤩 

Best 

Hegel991

**Comment by dschick** [comment]
Great & thanks!

You are very welcome

**Comment by Hegel991** [comment]
Hi, @dschick. Sorry to disturb you again.  I would like to make sure that my understanding is correct. As shown by the section 5.3. Examples in udkm1Dsim Documentation Release 1.5.6, the Strontium Ruthenate (SRO) can be built by the following scripts, 

SRO = ud.UnitCell('SRO', 'Strontium Ruthenate', c_SRO, **prop_SRO)
SRO.add_atom(O, 0)
SRO.add_atom(Sr, 0)
SRO.add_atom(O, 0.5)
SRO.add_atom(O, 0.5)
SRO.add_atom(Ru, 0.5)

I would like to know the  given number(i.e., 0, 0, 0.5, 0.5, 0.5) is obtained from the fractional coordinates as I got from the vasp file for Strontium Ruthenate.

I am looking forward to your reply.

Best regards!


![Position](https://github.com/dschick/udkm1Dsim/assets/79781683/d50d187e-6456-4527-ae8c-44cd1fc476c8)
![Strontium Ruthenate](https://github.com/dschick/udkm1Dsim/assets/79781683/1921a915-b27e-46a8-a097-7e230f1b66f5)
