### ISSUE TITLE
Can substrates only be crystalline / does it matter?

### ISSUE THREAD

**Issue by EmCeBeh** [dschick/udkm1Dsim#34]
It is not allowed to create an amorphous substrate directly:

```
SL = ud.Structure('Super Lattice')
substrate = ud.AmorphousLayer('Substrate','Substrate',500*u.nm,Si_uc.density)
SL.add_substrate(substrate)
```
As this will cause the following error:
`Class AmorphousLayer is no possible substrate. Only structure class is allowed!`

Should you create only crystalline substrate or can/should you do the following: 

```
SL = ud.Structure('Super Lattice')
subs = ud.AmorphousLayer('Substrate','Substrate',500*u.nm,Si_uc.density)
substrate = ud.Structure('Substrate')
substrate.add_sub_structure(subs)
SL.add_substrate(substrate)
```

And does it even matter computationally or physically?

**Comment by dschick** [comment]
hm, the substrate must be a structure in itself. Within the structure you should be able to add either amorphous or crystalline layers, or both.

The reason is actually to be able to use the same methods for the substrate as for the actual sample structure.
One could of course also allow directly amorphous and crystalline layers as substrate by automatically creating a structure around them.

**Comment by dschick** [comment]
The above error should be converted to a warning if valid at all
