### ISSUE TITLE
Different values for heat.intp_at_interface give different results in multi-pulse excitation

### ISSUE THREAD

**Issue by kathinkagerlinger** [dschick/udkm1Dsim#95]
There seems to be a numerical problem with the interpolation at surfaces with an excitation consisting of multiple pulses.
The result for a single pulse is always the same no matter the number of interpolation steps, however 5 consecutive pulses (20 ns apart = 50MHz) differ much for different values.

![interp_11](https://user-images.githubusercontent.com/36959852/134017140-eb2d5b48-df60-4304-8f23-5374e52ac5fb.png)
![interp_21](https://user-images.githubusercontent.com/36959852/134017144-02e3c5c8-a2bc-473b-ab61-49f56a879eb9.png)
![interp_51](https://user-images.githubusercontent.com/36959852/134017146-e403aebd-0431-4c96-b71c-f00a18b26bb8.png)

**Comment by dschick** [comment]
Hi @kathinkagerlinger 

thank you for this observation. I think it is a numerical issue which is linked to large delays time and pulse length.
For me using shorter delays in the ps-range, it seems to work fine.
The same happens if I use a delay grid with 100fs steps.

Could you verify this?
In principle the delay-grid should be automatically adapted to the pulse-duration and delay. However, it could be also related to the solver not liking large steps. 

Maybe the solver could be changed to another method
https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html
which is more appropriate for this problem.

**Comment by kathinkagerlinger** [comment]
Yes, taking 100fs time steps seems to do the trick! Thank you
![interp_11_100fs-timestep](https://user-images.githubusercontent.com/36959852/134530796-3eab6ccf-db70-4068-af1b-03d903130ca6.png)
![interp_21_100fs-timestep](https://user-images.githubusercontent.com/36959852/134530803-ca82ed38-5347-48f6-97e6-7bc94f4ae969.png)
![interp_51_100fs-timestep](https://user-images.githubusercontent.com/36959852/134530806-862fe4d3-11eb-4ffc-831d-a021dc7f5072.png)

**Comment by dschick** [comment]
still I am a bit puzzeled as the temporal grid, that is handed to the solver is already rather fine around the pump pulses.
Maybe the current solver does not like so to change the step width too often/much.

I am also wondering that your multi-pulse results do show some heating now, but still not very consistent with what one would expect.
